Improve documentation
secvisogram/csaf-validator-service pull request #33
Opened 2022-10-05 11:47 UTC by Id3aFly

When using the API first it was not clear at all how to use it. Here is a proposal that tries to improve the documentation.

2022-10-24 13:39 UTC, tschmidtb51 requested changes
Thank you for your contribution. Please also regenerate the docs using one of the methods described here: https://openapi-generator.tech/docs/installation/

We will automate that later in the process (see also #34).

2022-10-24 13:39 UTC, tschmidtb51 commented on backend/lib/app/validate.js
> +    'This endpoint is intended to validate a document against the specified tests. In the list of tests you need to provide at least one dict, where each dict is used to run either a single test or a
```suggestion
    'This endpoint is intended to validate a document against the specified tests. In the list of tests provide at least one object, where each object is used to run either a single test or an entire preset. For \'name\' provide the test\'s or the preset\'s name, and as \'type\' provide accordingly either \'test\' or \'preset\'. For the value of the property \'document\' just provide the json of your CSAF document.',

2022-10-26 13:03 UTC, Id3aFly commented
Regarding the openapi-generator: It requires a petstore.yaml. I did not find one in the repository. Can you share it maybe so I don't have to create it anew?

2022-10-26 13:35 UTC, tschmidtb51 commented
@domachine Please have a look whether we forgot that file or there is a different way to generate the documentation... Please comment here.

2022-10-28 12:34 UTC, domachine commented
Sorry, I can not find a reference to a file called `petstore.yaml` in the project. This sounds more like a sample file.

2022-10-28 12:37 UTC, Id3aFly commented
And do you use any other yaml file for this? If not I can try later to run the openapi-generator without this file.

2023-02-23 23:14 UTC, tschmidtb51 commented
Changed base to be able to edit things...

2023-02-23 23:14 UTC, merged