Set bodyLimit size to 10MB
secvisogram/csaf-validator-service pull request #37
Opened 2022-12-15 16:09 UTC by AntonW

We need an bigger fastify bodyLimit for documents bigger than 1MiB. We found documents larger than 7MiB.
This value is harcoded because the only possible configuration-options are via the config-package.
The fastify-env-plugin seems to be a better solution, but this requires an upgrade to fastify 4.X.

2022-12-20 13:55 UTC, tschmidtb51 requested changes
I'm sorry but I couldn't follow your explanation about the hardcoded-value. If it is possible via the config package, why don't you use that option? AFAIR we already set some values from a config file...

2022-12-20 13:55 UTC, tschmidtb51 commented on backend/server.js
> +    bodyLimit: 10048576
@AntonW I would prefer not to have that hard-coded here. Especially, not the "random" value of 10 MiB. The standard [suggests to use 15 MiB](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#c1-file-size).

2022-12-20 13:56 UTC, tschmidtb51 commented
@domachine: Any additional comments?

2022-12-29 22:35 UTC, AntonW commented
You can now configure the bodylimit using the configuration-files. As I wrote earlier: it would be better to use fastify-env. But this needs an upgrade to fastify 4.X

2023-01-04 04:23 UTC, domachine commented
> @domachine: Any additional comments?

No, and I don't understand why `fastify-env` should be superior to `config`, since it can map environment variables as well.

2023-01-09 21:51 UTC, tschmidtb51 commented on backend/server.js
> +    bodyLimit: 10048576
@AntonW Thanks for changing it.

2023-01-18 20:31 UTC, tschmidtb51 reviewed
One minor change, before ready to accept.

2023-01-18 20:31 UTC, tschmidtb51 commented on backend/config/default.json
> +  "bodyLimit": 15000000
As discussed today:
```suggestion
  "bodyLimit": 15728640

2023-01-20 16:45 UTC, tschmidtb51 commented on backend/config/default.json
> +  "bodyLimit": 15000000
As discussed in the CSAF Editor meeting this should be 15728640 bytes.

2023-01-20 16:45 UTC, tschmidtb51 commented on backend/config/development.json
> +  "bodyLimit": 15000000
As discussed in the CSAF Editor meeting this should be 15728640 bytes.

2023-01-20 16:48 UTC, tschmidtb51 approved these changes
LGTM.

2023-01-20 16:51 UTC, sthagen approved these changes
From the sidelines (as co-editor of CSAF v2.0) please use the multiples of 2 measure `15 * (2**20)` as the target of the limit is to avoid storage / memory related problems.

2023-01-20 16:52 UTC, merged